In [83]:
import numpy as np
import random
from numpy import linalg as la

#1 Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно
a = np.arange(12, 24, 1)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [84]:
#2 Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.
b1 = np.array([list(a[0:1:1]), list(a[6:7:1])] )
b1
b2 = np.array([list(a[0:2:1]), list(a[6:8:1])] )
b2
b3 = np.array([list(a[0:3:1]), list(a[6:9:1])] )
b3
b4 = np.array([list(a[0:4:1]), list(a[6:10:1])] )
b4
b5 = np.array([list(a[0:5:1]), list(a[6:11:1])] )
b5

array([[12, 13, 14, 15, 16],
       [18, 19, 20, 21, 22]])

In [85]:
#2 Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.
c = []
for i in range(1, 6):
    c.append(np.array([list(a[0:i:1]), list(a[6:6+i:1])]))
c

[array([[12],
        [18]]),
 array([[12, 13],
        [18, 19]]),
 array([[12, 13, 14],
        [18, 19, 20]]),
 array([[12, 13, 14, 15],
        [18, 19, 20, 21]]),
 array([[12, 13, 14, 15, 16],
        [18, 19, 20, 21, 22]])]

In [86]:
#3 Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).
c = []
for i in range(1, 6):
    c.append(np.array([list(a[i:i+2:1]), list(a[5+i:7+i:1])]))
c

[array([[13, 14],
        [18, 19]]),
 array([[14, 15],
        [19, 20]]),
 array([[15, 16],
        [20, 21]]),
 array([[16, 17],
        [21, 22]]),
 array([[17, 18],
        [22, 23]])]

In [87]:
#4 Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?
# ДА!

In [88]:
#5Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив
mu = 0
sigma = 1.0
c = []
for i in range(1, 13):
    c.append(random.normalvariate(mu, sigma))


b1 = np.array([list(c[0:4:1]), list(c[4:8:1]), list(c[8:12:1]) ] )


c1=[]
for i in range(len(b1)):
    for j in range (len(b1[i])):
        c1.append(b1[i][j])
        
c1    

[-0.3687628978706958,
 -0.07953590788064414,
 -0.9554292602868603,
 1.0358544166041672,
 1.2190969837971581,
 1.0142595685404097,
 -0.48180195090443456,
 -0.8976267475391253,
 0.9790748685208328,
 0.339093224546072,
 0.49705692829450265,
 -0.8141185646505908]

In [89]:
#6Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [90]:
#7Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?
b = np.arange(20, 1, -2)
b

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [91]:
#9
d = np.arange(0, 12, 1)
A = np.array([list(d[0:3:1]), list(d[3:6:1]), list(d[6:9:1]),list(d[9:12:1])])
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [92]:
At = A.transpose()
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [93]:
B = np.matmul(A, At, out=None)
B
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [94]:
B_inv = la.inv(B)
B_inv
#ОБРАТНАЯ МАТРИЦА НЕ СУЩЕСИТВУЕТ МАТРИЦА СИНГУЛЯРНАЯ



LinAlgError: Singular matrix

In [95]:
# детерминант равен нулю  обратная матрица не существует
la.det(B)

0.0

In [96]:
#10 Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.
random.seed(42)
random.random()

0.6394267984578837

In [105]:
#Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 
mas=[] 
for i in range(16): 
    mas.append(random.randint(0, 16))

m = np.array(mas)
m

array([13,  7, 14,  8,  0,  5, 13, 10,  8,  4,  6, 10,  3,  2, 12,  3])

In [106]:
C = m.reshape(4,4)
C


array([[13,  7, 14,  8],
       [ 0,  5, 13, 10],
       [ 8,  4,  6, 10],
       [ 3,  2, 12,  3]])

In [153]:
B = m*10
B

array([130,  70, 140,  80,   0,  50, 130, 100,  80,  40,  60, 100,  30,
        20, 120,  30])

In [154]:
D = np.zeros(4)
S=0
for i in range(len(B1)):
    S = S + B1[i]

D = C + S
D

array([[1193, 1187, 1194, 1188],
       [1180, 1185, 1193, 1190],
       [1188, 1184, 1186, 1190],
       [1183, 1182, 1192, 1183]])

In [155]:
# детерминант равен нулю  обратная матрица не существует для матрицы D
la.det(D)

-21800.00000001108

In [156]:
D_inv = la.inv(D)
D_inv

array([[-1.1887156 , -0.82633028,  0.65986239,  1.36119266],
       [ 6.42651376,  3.87146789, -3.29105505, -7.03752294],
       [-2.2766055 , -1.35458716,  1.08142202,  2.56100917],
       [-2.93844037, -1.67697248,  1.53876147,  3.09073394]])

In [157]:
#13 Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы
for i in range(len(D_inv)):
    for j in range(len(D_inv[i])):
        if (D_inv[i][j] < 0 ):
            D_inv[i][j] = 0.0
        else:
             D_inv[i][j] = 1.0                

D_inv
            

array([[0., 0., 1., 1.],
       [1., 1., 0., 0.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [162]:
E= np.where(D_inv == 0, C, D)
E

array([[  13,    7, 1194, 1188],
       [1180, 1185,   13,   10],
       [   8,    4, 1186, 1190],
       [   3,    2, 1192, 1183]])